export const initialCategories = [
  {
    id: 1,
    name: "Food",
    type: "expense",
    icon: "fastfood",
    budget: 0,
    isEnabled: false,
    entries: [],
  },
  {
    id: 2,
    name: "Bills",
    type: "expense",
    icon: "receipt",
    budget: 0,
    isEnabled: false,
    entries: [],
  },
  {
    id: 3,
    name: "Car Insurance",
    type: "expense",
    icon: "directions_car_icon",
    budget: 0,
    isEnabled: false,
    entries: [],
  },
  {
    id: 4,
    name: "Rent",
    type: "income",
    icon: "bedroom_parent_icon",
    budget: 0,
    isEnabled: false,
    entries: [],
  },
  {
    id: 5,
    name: "Crypto Investments",
    type: "income",
    icon: "currency_bitcoin_icon",
    budget: 0,
    isEnabled: false,
    entries: [],
  },
  {
    id: 6,
    name: "Salary",
    type: "income",
    icon: "attach_money_icon",
    budget: 0,
    isEnabled: false,
    entries: [],
  },
];

export const icons = [
  "accessibility",
  "account_balance",
  "airplanemode_active",
  "add_box_icon",
  "airport_shuttle_icon",
  "apartment_icon",
  "currency_exchange_icon"
];
